name: Publish KDoc

on: [ push ]

env:
  GIT_REF: ${{ github.ref }}
  SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
  SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
  SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
  OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
  OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}

jobs:
  ubuntu:
    name: "Publish KDoc"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build KDoc
        run: ./gradlew clean dokkaHtml
      - name: Publish KDoc
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: build/dokka/html
